apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adapters.coinmarketcap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adapters.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.coinmarketcap.replicaCount }}
  selector:
    matchLabels:
      {{- include "adapters.coinmarketcap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.coinmarketcap.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adapters.coinmarketcap.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.coinmarketcap.name }}
          image: "{{ .Values.coinmarketcap.image.repository }}:{{ .Values.coinmarketcap.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.coinmarketcap.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.coinmarketcap.service.port }}
              protocol: TCP
          env:
            - name: EA_PORT
              value: {{ .Values.coinmarketcap.config.ea_port | quote }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "adapters.coinmarketcap.fullname" . }}
                  key: api-key
            - name: TIMEOUT
              value: {{ .Values.coinmarketcap.config.timeout | quote }}
            - name: CACHE_ENABLED
              value: {{ .Values.coinmarketcap.config.cache_enabled | quote }}
            - name: RATE_LIMIT_ENABLED
              value: {{ .Values.coinmarketcap.config.rate_limit_enabled | quote }}
            - name: WARMUP_ENABLED
              value: {{ .Values.coinmarketcap.config.warmup_enabled | quote }}
            - name: RATE_LIMIT_API_PROVIDER
              value: {{ .Values.coinmarketcap.config.rate_limit_api_provider | quote }}
            - name: RATE_LIMIT_API_TIER
              value: {{ .Values.coinmarketcap.config.rate_limit_api_tier | quote }}
            - name: REQUEST_COALESCING_ENABLED
              value: {{ .Values.coinmarketcap.config.request_coalescing_enabled | quote }}
            - name: REQUEST_COALESCING_INTERVAL
              value: {{ .Values.coinmarketcap.config.request_coalescing_interval | quote }}
            - name: REQUEST_COALESCING_INTERVAL_MAX
              value: {{ .Values.coinmarketcap.config.request_coalescing_interval_max | quote }}
            - name: REQUEST_COALESCING_INTERVAL_COEFFICIENT
              value: {{ .Values.coinmarketcap.config.request_coalescing_interval_coefficient | quote }}
            - name: REQUEST_COALESCING_ENTROPY_MAX
              value: {{ .Values.coinmarketcap.config.request_coalescing_entropy_max | quote }}
            - name: WARMUP_UNHEALTHY_THRESHOLD
              value: {{ .Values.coinmarketcap.config.warmup_unhealthy_treshold | quote }}
            - name: WARMUP_SUBSCRIPTION_TTL
              value: {{ .Values.coinmarketcap.config.warmup_subscription_ttl | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.coinmarketcap.config.log_level | quote }}
            - name: DEBUG
              value: {{ .Values.coinmarketcap.config.debug | quote }}
            - name: API_VERBOSE
              value: {{ .Values.coinmarketcap.config.api_verbose | quote }}
            - name: EXPERIMENTAL_METRICS_ENABLED
              value: {{ .Values.coinmarketcap.config.experimental_metrics_enabled | quote }}
            - name: METRICS_NAME
              value: {{ .Values.coinmarketcap.config.metrics_name | quote }}
            - name: RETRY
              value: {{ .Values.coinmarketcap.config.retry | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.coinmarketcap.resources | nindent 12 }}
      {{- with .Values.coinmarketcap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coinmarketcap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.coinmarketcap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
