{{- if .Values.tiingo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adapters.tiingo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adapters.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{.Values.tiingo.config.api_key | b64enc}}
  {{- end }}
