apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chainlink.fullname" . }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      name: {{ include "chainlink.fullname" . }}
    spec:
      serviceAccountName: {{ include "chainlink.fullname" . }}-post-install
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          image: "bitnami/kubectl:latest"
          command:
            - "bin/bash"
            - "-c"
            - >
              kubectl scale statefulset chainlink --replicas {{ .Values.replicaCount }}
  ttlSecondsAfterFinished: 300
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chainlink.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "chainlink.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "chainlink.fullname" . }}-post-install
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
subjects:
  - kind: ServiceAccount
    name: {{ include "chainlink.fullname" . }}-post-install
roleRef:
  kind: Role
  name: {{ include "chainlink.fullname" . }}-post-install
  apiGroup: rbac.authorization.k8s.io
