apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainlink.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chainlink.labels" . | nindent 4 }}
type: Opaque
data:
  db-url: {{.Values.config.db_url | b64enc}}
