{{- if .Values.bea.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adapters.bea.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adapters.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{.Values.bea.config.api_key | b64enc}}
  {{- end }}
