nomics:
  name: "nomics"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/nomics-adapter
    pullPolicy: Always
    tag: latest

  config:
    ea_port: 1111
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'nomics'
    rate_limit_api_tier: "https://api.nomics.com/v1"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: nomics
    retry: 1

  service:
    port: 1111

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

cryptocompare:
  name: "cryptocompare"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/cryptocompare-adapter
    pullPolicy: Always
    tag: latest

  config:
    ea_port: 1114
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'cryptocompare'
    rate_limit_api_tier: "https://min-api.cryptocompare.com/data/price"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: cryptocompare
    retry: 1

  service:
    port: 1114


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"
    prometheus.io/metrics-prefix: "adapters-pods"

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

tiingo:
  name: "tiingo"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/tiingo-adapter
    pullPolicy: Always
    tag: latest

  config:
    ea_port: 1134
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'tiingo'
    rate_limit_api_tier: "https://api.tiingo.com/api/test"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: tiingo
    retry: 1

  service:
    port: 1134


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

coingecko:
  name: "coingecko"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/coingecko-adapter
    pullPolicy: Always
    tag: latest

  config:
    ea_port: 1113
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'coingecko'
    rate_limit_api_tier: "https://api.coingecko.com/api/v3/"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: coingecko
    retry: 1

  service:
    port: 1113


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

coinmarketcap:
  name: "coinmarketcap"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/coinmarketcap-adapter
    pullPolicy: Always
    tag: latest

  config:
    ea_port: 1115
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'coinmarketcap'
    rate_limit_api_tier: "https://api.coinmarketcap.com/api/test"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: coinmarketcap
    retry: 1

  service:
    port: 1115


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

jpegd:
  name: "jpegd"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/jpegd-adapter
    pullPolicy: Always
    tag: 2.1.16

  config:
    ea_port: 1171
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'jpegd'
    rate_limit_api_tier: "https://jpegapi.com"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: jpegd
    retry: 1

  service:
    port: 1171


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

bea:
  name: "bea"
  replicaCount: 1

  image:
    repository: public.ecr.aws/chainlink/adapters/bea-adapter
    pullPolicy: Always
    tag: 1.3.19

  config:
    ea_port: 2232
    api_key: "fake"
    timeout: 30000
    cache_enabled: false
    rate_limit_enabled: true
    warmup_enabled: true
    rate_limit_api_provider: 'bea'
    rate_limit_api_tier: "https://apps.bea.gov"
    request_coalescing_enabled: true
    request_coalescing_interval: 100
    request_coalescing_interval_max: 1000
    request_coalescing_interval_coefficient: 2
    request_coalescing_entropy_max: 0
    warmup_unhealthy_treshold: 3
    warmup_subscription_ttl: 3600000
    log_level: "info"
    debug: false
    api_verbose: false
    experimental_metrics_enabled: true
    metrics_name: bea
    retry: 1

  service:
    port: 2232


  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9080"

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
