apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chainlink.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "chainlink.selectorLabels" . | nindent 6 }}
