apiVersion: v1
kind: Service
metadata:
  name: {{ include "adapters.jpegd.fullname" . }}
  labels:
    {{- include "adapters.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.jpegd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9080
      targetPort: 9080
      protocol: TCP
      name: prometheus
  selector:
    {{- include "adapters.jpegd.selectorLabels" . | nindent 4 }}
