{
 "title": "OffChainReporting Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus_DS", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Loki_DS", "query": "loki" },
   { "name": "job", "label": "Chainlink Node", "query": { "query": "label_values(job)" } },
   { "name": "name", "label": "Container Name", "query": "label_values(container_name)" }
  ]
 },
 "panels": [
  {
   "title": "Chainlink Node Container/Pod Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  { "title": "Chainlink Node Label", "type": "text", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 }, "options": { "content": "# $job" } },
  {
   "title": "Total Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime_seconds{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Node Balance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_balance{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Usage",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"localhost:9100\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"localhost:9100\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"localhost:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Health Status Services",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "health{job=\"$job\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Health Status Services",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health{job=\"$job\"}",
     "legendFormat": "{{service_id}}"
    }
   ]
  },
  {
   "title": "Node Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_balance{job=\"$job\"}",
     "legendFormat": "Account={{account}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"localhost:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"localhost:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 12 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "$job"
    }
   ]
  },
  { "title": "Blockchain Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Connection Errors [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(head_tracker_eth_connection_errors{job=\"$job\"}[24h])"
    }
   ]
  },
  {
   "title": "Current Chain Head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "head_tracker_current_head{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Avg. Blocks/min",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(head_tracker_heads_received{job=\"$job\"}[5m]) / 5"
    }
   ]
  },
  {
   "title": "Avg. Blocks/min   [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(head_tracker_heads_received{job=\"$job\"}[24h]) / 1440"
    }
   ]
  },
  {
   "title": "Incoming Blocks By Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "head_tracker_current_head{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Very Old Heads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "head_tracker_very_old_head{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blockchain Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(head_tracker_eth_connection_errors{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Incoming Blocks/min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(head_tracker_heads_received{job=\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Reverted Txns [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(tx_manager_num_tx_reverted{job=\"$job\"}[24h])"
    }
   ]
  },
  {
   "title": "Total Bumped Txns [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(unconfirmed_transactions{job=\"$job\"}[24h])"
    }
   ]
  },
  {
   "title": "Unconfirmd Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_unconfirmed_blocks{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tx_manager_num_successful_transactions{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gas Bumps Txns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(tx_manager_num_gas_bumps{job=\"$job\"}[10m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gas Price [all]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "expr": "gas_updater_all_gas_percetiles{job=\"$job\"} / 1000000000",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "Gas Price [70%]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gas_updater_all_gas_percetiles{job=\"$job\", percentile=\"70%\"} / 1000000000",
     "legendFormat": "{{job}} [70%]"
    }
   ]
  },
  {
   "title": "Total Reverted Txns [5min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "increase(tx_manager_num_tx_reverted{job=\"$job\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Off-Chain Reporting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Task Errors [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pipeline_tasks_total_finished{status=\"error\",task_type=\"bridge\",job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "Datasource Errors [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pipeline_run_errors{job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "Queued Runs [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pipeline_runs_queued{job=\"$job\"}[24h])"
    }
   ]
  },
  {
   "title": "Datasource ERROR runs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 3, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pipeline_run_errors{job=\"$job\"}[10m])",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Pipeline Task Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pipeline_tasks_total_finished{status=\"error\",task_type=\"bridge\",job=\"$job\"}[5m])",
     "legendFormat": "{{task_id}} {{job_name}}"
    }
   ]
  },
  {
   "title": "Queued Runs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pipeline_runs_queued{job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Job Run Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pipeline_run_total_time_to_completion{job=\"$job\"} / 1000000000",
     "legendFormat": "id={{job_id}} name={{job_name}}"
    }
   ]
  },
  { "title": "Logging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "[ERROR] Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "{container_name=\"$name\"} |~ \"ERROR]\""
    }
   ]
  },
  {
   "title": "[WARN] Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "{container_name=\"$name\"} |~ \"WARN]\""
    }
   ]
  },
  {
   "title": "Adapter Error Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "{container_name=\"$name\"} |~ \"adapter got error\""
    }
   ]
  },
  {
   "title": "[ERROR] Logs [5min]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"$name\"} |~ \"ERROR]\"[5m]))",
     "legendFormat": "[ERROR]"
    }
   ]
  },
  {
   "title": "[WARN] Logs [5min]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"$name\"} |~ \"WARN]\"[5m]))",
     "legendFormat": "[WARN]"
    }
   ]
  },
  {
   "title": "[ERROR] Logs [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"$name\"} |~ \"ERROR]\"[24h]))"
    }
   ]
  },
  {
   "title": "[WARN] Logs [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"$name\"} |~ \"WARN]\"[24h]))"
    }
   ]
  },
  {
   "title": "Adapter Error [24h]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 112 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container_name=\"$name\"} |~ \"adapter got error\"[24h]))"
    }
   ]
  }
 ]
}