{
 "title": "External-Adapter Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Adapter Container Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "API Calls/min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status_code=\"2XX\",type=\"dataProviderHit\"}[1m]))"
    }
   ]
  },
  { "title": "Adapter Label", "type": "text", "gridPos": { "h": 4, "w": 6, "x": 3, "y": 4 }, "options": { "content": "# $job" } },
  {
   "title": "API Calls [24h]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status_code=\"2XX\",type=\"dataProviderHit\"}[24h]))"
    }
   ]
  },
  {
   "title": "API Errors [24h]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status_code=\"5XX\",job=\"$job\"}[24h]))"
    }
   ]
  },
  {
   "title": "API Calls Saved",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-((sum(increase(http_requests_total{job=\"$job\",status_code=\"2XX\",type=\"dataProviderHit\"}[1m])))/(sum(increase(http_requests_total{job=\"$job\"}[1m])))))*100"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "Adapter Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "EA Call Overview",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"$job\"}[5m]) * 60) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "API Calls/min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\",status_code=\"2XX\",type=\"dataProviderHit\"}[1m]))",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "API Calls Saved",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "(1-((sum(increase(http_requests_total{job=\"$job\",status_code=\"2XX\",type=\"dataProviderHit\"}[1m])))/(sum(increase(http_requests_total{job=\"$job\"}[1m])))))*100",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "EA Calls/min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"$job\"}[1m]))",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "Total Rate Limit Credits/24h",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(rate_limit_credits_spent_total{job=\"$job\"}[24h]))",
     "legendFormat": "$job"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Average Data Provider Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cache_execution_duration_seconds_sum{cache_hit=\"false\",job=\"$job\"}[5m]))\n/\nsum(rate(cache_execution_duration_seconds_count{cache_hit=\"false\",job=\"$job\"}[5m]))",
     "legendFormat": "$job"
    }
   ]
  },
  {
   "title": "Average Cache Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cache_execution_duration_seconds_sum{job=\"$job\",cache_hit=\"true\"}[5m])) / sum(rate(cache_execution_duration_seconds_count{job=\"$job\",cache_hit=\"true\"}[5m]))",
     "legendFormat": "$job"
    }
   ]
  },
  { "title": "Feed Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Rate Limitation Credits Spent/Feed",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rate_limit_credits_spent_total{job=\"$job\"}[5m]) * 60) by (feed_id)",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "Error Calls/Feed",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "increase(http_requests_total{status_code=\"5XX\",job=\"$job\"}[2m])",
     "legendFormat": "{{feed_id}}"
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status_code=\"5XX\",job=\"$job\"}[2m]))",
     "legendFormat": "[5xx] Status Code"
    }
   ]
  }
 ]
}