{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chainlink",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"chainlink-\"",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  { "title": "Adapters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Coingecko",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"coingecko-\"\n",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Coinmarketcap",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"coinmarketcap-\"",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Cryptocompare",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"cryptocompare-\"",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "jpegd",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"jpegd-\"",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Nomics",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expression": "fields log\n| filter @logStream like \"nomics-\"",
     "logGroupNames": [
      "/aws/containerinsights/chainlink-dev/application"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}