apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adapters.nomics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adapters.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{.Values.nomics.config.api_key | b64enc}}
